const fs = require('fs');
const { execFileSync } = require('child_process');
process.chdir('D:/mobby/mobidou');
const ff = process.env.FFMPEG;
const probe = ff.replace('ffmpeg.exe', 'ffprobe.exe');
const slices = JSON.parse(fs.readFileSync('assets/ui-round3/slices.json', 'utf8'));

function measure(file) {
  const dims = execFileSync(probe, ['-v', 'error', '-show_entries', 'stream=width,height', '-of', 'csv=p=0', file]).toString().trim().split(',');
  const w = +dims[0], h = +dims[1];
  const alpha = execFileSync(ff, ['-v', 'error', '-i', file, '-vf', 'alphaextract,format=gray', '-f', 'rawvideo', '-pix_fmt', 'gray', '-'], { maxBuffer: w * h * 2 });
  let x0 = w, y0 = h, x1 = -1, y1 = -1;
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) if (alpha[y * w + x] > 40) { if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y; }
  return { w, h, x0, x1: x1 + 1, y0, y1: y1 + 1 };
}
const camel = name => name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const groups = [['ui', 'assets/ui-round3/ui'], ['opening', 'assets/ui-round3/opening']];
const lines = ['// Generated by scripts/gen-ui-art.cjs from assets/ui-round3. `box` is the artwork inside the picture, in pixels;',
  '// `slice` is the fixed edge width/height of stretchable parts, in pixels from the picture edge.',
  "import type { ImageSourcePropType } from 'react-native';",
  '',
  'export type UiArt = { source: ImageSourcePropType; width: number; height: number; box: { x0: number; x1: number; y0: number; y1: number }; slice?: { left?: number; right?: number; top?: number; bottom?: number } };',
  '', 'export const UI_ART = {'];
for (const [group, dir] of groups) {
  for (const f of fs.readdirSync(dir).filter(n => n.endsWith('.webp')).sort()) {
    const file = `${dir}/${f}`;
    const m = measure(file);
    const key = camel(f.replace('.webp', ''));
    const slice = slices[`${group}/${f}`];
    lines.push(`  ${key}: { source: require('../../${file}'), width: ${m.w}, height: ${m.h}, box: { x0: ${m.x0}, x1: ${m.x1}, y0: ${m.y0}, y1: ${m.y1} }${slice ? `, slice: ${JSON.stringify(slice).replace(/"/g, '')}` : ''} },`);
  }
}
lines.push('} as const satisfies Record<string, UiArt>;', '', 'export type UiArtName = keyof typeof UI_ART;', '');
fs.writeFileSync('src/data/uiArt.ts', lines.join('\n'));
console.log('ok');
