import type { ImageSourcePropType } from 'react-native';

import type { CoreMobbyId } from './mobbyPullAssets';

/**
 * PNG copies of the pull bodies with the character silhouette already baked in,
 * for the expo-gl build (expo-gl can't decode WebP). Generated by
 * scripts/build-pull-gl-textures.cjs.
 */
export const PULL_GL_TEXTURES: Record<CoreMobbyId, ImageSourcePropType> = {
  mobirin: require('../../assets/mobies/pull/gl/mobirin-body.png'),
  mobichi: require('../../assets/mobies/pull/gl/mobichi-body.png'),
  yami: require('../../assets/mobies/pull/gl/yami-body.png'),
  mobiyan: require('../../assets/mobies/pull/gl/mobiyan-body.png'),
  mobiyura: require('../../assets/mobies/pull/gl/mobiyura-body.png'),
  reomoby: require('../../assets/mobies/pull/gl/reomoby-body.png'),
  potemoby: require('../../assets/mobies/pull/gl/potemoby-body.png'),
  mobibou: require('../../assets/mobies/pull/gl/mobibou-body.png'),
  babumoby: require('../../assets/mobies/pull/gl/babumoby-body.png'),
};
