// Generated by scripts/measure-pull-part-anchors.cjs. Centers as fractions of the pull canvas.
export type PullPartAnchors = Record<'lens' | 'cross' | 'buttonLeft' | 'buttonRight', { x: number; y: number }>;
export const PULL_PART_ANCHORS: Record<string, PullPartAnchors> = {
  mobirin: { lens: { x: 0.636, y: 0.3489 }, cross: { x: 0.3628, y: 0.5921 }, buttonLeft: { x: 0.5682, y: 0.5662 }, buttonRight: { x: 0.6475, y: 0.5443 } },
  mobichi: { lens: { x: 0.6388, y: 0.327 }, cross: { x: 0.3565, y: 0.5203 }, buttonLeft: { x: 0.5463, y: 0.5167 }, buttonRight: { x: 0.6419, y: 0.4833 } },
  yami: { lens: { x: 0.618, y: 0.3509 }, cross: { x: 0.3549, y: 0.5463 }, buttonLeft: { x: 0.5622, y: 0.5303 }, buttonRight: { x: 0.6459, y: 0.5124 } },
  mobiyan: { lens: { x: 0.628, y: 0.3808 }, cross: { x: 0.3923, y: 0.614 }, buttonLeft: { x: 0.5901, y: 0.5901 }, buttonRight: { x: 0.6659, y: 0.5582 } },
  mobiyura: { lens: { x: 0.6256, y: 0.3549 }, cross: { x: 0.3939, y: 0.6025 }, buttonLeft: { x: 0.5881, y: 0.61 }, buttonRight: { x: 0.6563, y: 0.5961 } },
  reomoby: { lens: { x: 0.6276, y: 0.3549 }, cross: { x: 0.3951, y: 0.6041 }, buttonLeft: { x: 0.5921, y: 0.612 }, buttonRight: { x: 0.6471, y: 0.6639 } },
  potemoby: { lens: { x: 0.632, y: 0.321 }, cross: { x: 0.4131, y: 0.4621 }, buttonLeft: { x: 0.5861, y: 0.449 }, buttonRight: { x: 0.6423, y: 0.4302 } },
  mobibou: { lens: { x: 0.6459, y: 0.3608 }, cross: { x: 0.3927, y: 0.5981 }, buttonLeft: { x: 0.5965, y: 0.5977 }, buttonRight: { x: 0.6842, y: 0.5702 } },
  babumoby: { lens: { x: 0.614, y: 0.3967 }, cross: { x: 0.3868, y: 0.6483 }, buttonLeft: { x: 0.5805, y: 0.6579 }, buttonRight: { x: 0.6495, y: 0.624 } },
};
