// Generated by scripts/gen-ui-art.cjs from assets/ui-round3. `box` is the artwork inside the picture, in pixels;
// `slice` is the fixed edge width/height of stretchable parts, in pixels from the picture edge.
import type { ImageSourcePropType } from 'react-native';

export type UiArt = { source: ImageSourcePropType; width: number; height: number; box: { x0: number; x1: number; y0: number; y1: number }; slice?: { left?: number; right?: number; top?: number; bottom?: number } };

export const UI_ART = {
  badgeCount: { source: require('../../assets/ui-round3/ui/badge-count.webp'), width: 128, height: 128, box: { x0: 7, x1: 121, y0: 6, y1: 122 } },
  buttonDisabled: { source: require('../../assets/ui-round3/ui/button-disabled.webp'), width: 1400, height: 320, box: { x0: 12, x1: 1390, y0: 12, y1: 310 }, slice: {left:150,right:150} },
  buttonPrimaryPressed: { source: require('../../assets/ui-round3/ui/button-primary-pressed.webp'), width: 1400, height: 320, box: { x0: 16, x1: 1385, y0: 16, y1: 305 }, slice: {left:150,right:150} },
  buttonPrimary: { source: require('../../assets/ui-round3/ui/button-primary.webp'), width: 1400, height: 320, box: { x0: 16, x1: 1387, y0: 16, y1: 309 }, slice: {left:150,right:150} },
  buttonSecondaryPressed: { source: require('../../assets/ui-round3/ui/button-secondary-pressed.webp'), width: 1400, height: 320, box: { x0: 12, x1: 1389, y0: 12, y1: 309 }, slice: {left:150,right:150} },
  buttonSecondary: { source: require('../../assets/ui-round3/ui/button-secondary.webp'), width: 1400, height: 320, box: { x0: 12, x1: 1390, y0: 12, y1: 310 }, slice: {left:150,right:150} },
  cardFrameInset: { source: require('../../assets/ui-round3/ui/card-frame-inset.webp'), width: 1024, height: 512, box: { x0: 52, x1: 973, y0: 52, y1: 461 }, slice: {left:100,right:100,top:80,bottom:80} },
  cardFrame: { source: require('../../assets/ui-round3/ui/card-frame.webp'), width: 1024, height: 1024, box: { x0: 54, x1: 974, y0: 58, y1: 973 }, slice: {left:120,right:120,top:120,bottom:120} },
  focusFrame: { source: require('../../assets/ui-round3/ui/focus-frame.webp'), width: 640, height: 640, box: { x0: 41, x1: 600, y0: 41, y1: 600 }, slice: {left:100,right:100,top:100,bottom:100} },
  hintFrame: { source: require('../../assets/ui-round3/ui/hint-frame.webp'), width: 1000, height: 340, box: { x0: 14, x1: 989, y0: 13, y1: 329 }, slice: {left:110,right:110,top:90,bottom:90} },
  inputFrame: { source: require('../../assets/ui-round3/ui/input-frame.webp'), width: 1200, height: 260, box: { x0: 13, x1: 1190, y0: 13, y1: 253 }, slice: {left:130,right:130} },
  lockTag: { source: require('../../assets/ui-round3/ui/lock-tag.webp'), width: 160, height: 160, box: { x0: 14, x1: 148, y0: 15, y1: 151 } },
  pillStripDark: { source: require('../../assets/ui-round3/ui/pill-strip-dark.webp'), width: 900, height: 140, box: { x0: 5, x1: 898, y0: 4, y1: 139 }, slice: {left:90,right:90} },
  pillStrip: { source: require('../../assets/ui-round3/ui/pill-strip.webp'), width: 900, height: 140, box: { x0: 9, x1: 893, y0: 8, y1: 138 }, slice: {left:90,right:90} },
  progressFill: { source: require('../../assets/ui-round3/ui/progress-fill.webp'), width: 1200, height: 48, box: { x0: 28, x1: 1172, y0: 13, y1: 36 }, slice: {left:60,right:60} },
  progressPoint: { source: require('../../assets/ui-round3/ui/progress-point.webp'), width: 96, height: 96, box: { x0: 7, x1: 89, y0: 7, y1: 88 } },
  progressTrack: { source: require('../../assets/ui-round3/ui/progress-track.webp'), width: 1200, height: 48, box: { x0: 28, x1: 1172, y0: 13, y1: 37 }, slice: {left:60,right:60} },
  roundButtonPressed: { source: require('../../assets/ui-round3/ui/round-button-pressed.webp'), width: 256, height: 256, box: { x0: 20, x1: 235, y0: 20, y1: 237 } },
  roundButton: { source: require('../../assets/ui-round3/ui/round-button.webp'), width: 256, height: 256, box: { x0: 20, x1: 236, y0: 24, y1: 235 } },
  routeNodeDone: { source: require('../../assets/ui-round3/ui/route-node-done.webp'), width: 96, height: 96, box: { x0: 10, x1: 86, y0: 11, y1: 86 } },
  routeNodeTodo: { source: require('../../assets/ui-round3/ui/route-node-todo.webp'), width: 96, height: 96, box: { x0: 7, x1: 89, y0: 8, y1: 89 } },
  sealDisc: { source: require('../../assets/ui-round3/ui/seal-disc.webp'), width: 256, height: 256, box: { x0: 20, x1: 233, y0: 20, y1: 234 } },
  shadowBlot: { source: require('../../assets/ui-round3/ui/shadow-blot.webp'), width: 400, height: 100, box: { x0: 30, x1: 355, y0: 22, y1: 81 } },
  switchKnob: { source: require('../../assets/ui-round3/ui/switch-knob.webp'), width: 96, height: 96, box: { x0: 6, x1: 90, y0: 6, y1: 91 } },
  switchTrackOff: { source: require('../../assets/ui-round3/ui/switch-track-off.webp'), width: 240, height: 120, box: { x0: 8, x1: 232, y0: 17, y1: 104 } },
  switchTrackOn: { source: require('../../assets/ui-round3/ui/switch-track-on.webp'), width: 240, height: 120, box: { x0: 7, x1: 234, y0: 17, y1: 104 } },
  tileFrameEmpty: { source: require('../../assets/ui-round3/ui/tile-frame-empty.webp'), width: 400, height: 488, box: { x0: 16, x1: 385, y0: 16, y1: 473 }, slice: {left:64,right:64,top:72,bottom:72} },
  tileFrame: { source: require('../../assets/ui-round3/ui/tile-frame.webp'), width: 400, height: 488, box: { x0: 20, x1: 383, y0: 22, y1: 472 }, slice: {left:64,right:64,top:72,bottom:72} },
  openingCopyPlate: { source: require('../../assets/ui-round3/opening/opening-copy-plate.webp'), width: 1200, height: 420, box: { x0: 25, x1: 1178, y0: 24, y1: 402 } },
  openingHintPlate: { source: require('../../assets/ui-round3/opening/opening-hint-plate.webp'), width: 1000, height: 200, box: { x0: 17, x1: 979, y0: 30, y1: 152 } },
  openingSwipeCue: { source: require('../../assets/ui-round3/opening/opening-swipe-cue.webp'), width: 256, height: 256, box: { x0: 50, x1: 205, y0: 37, y1: 183 } },
} as const satisfies Record<string, UiArt>;

export type UiArtName = keyof typeof UI_ART;
